server:
  port: 9992
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
spring:
  application:
    name: Setting-Service
  config:
    import: optional:configserver:${CONFIG_SERVER_ENDPOINT:http://localhost:9999}
  datasource:
    driver-class-name: ${DRIVER_CLASS_NAME:org.postgresql.Driver}
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/setting-service}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    hikari:
      schema: public